const userModel = require("../models/User");
const bcrypt = require('bcrypt');
const jwt = require('jsonwebtoken');

const register = async(req,res)=>{
    try{
        const{name,email,password}=req.body;

        //all fileds are required 
        if(!name || !email || !password ){
            return res.status(400).json({
                message:"All fields are required"
            });
        };

        //check if email already exist
        const isAlreadyRegistered = await userModel.findOne({email});
        if(isAlreadyRegistered){
            return res.status(409).json({
                message:"Email already exist!"
            });
        };

        //set password to bcrypt.hash()
        const hashedPassword = await bcrypt.hash(password,10);

        //create new user with hashed password
        const user = await userModel.create({
            name,
            email,
            password:hashedPassword,
            // role,// no role here — schema default "student" applies automatically
        });
        return res.status(201).json({
            message:"User Registered succesfully!",
            user:{
                name:user.name,
                email:user.email,
                role:user.role,
            }
        });
    }catch(error){
        return res.status(500).json({
            message:error.message
        });
    };
};

const login = async(req,res)=>{
    try{
        //for login we send email and password
        const{email,password}=req.body;

        //check user has provided user and password
        if(!email || !password){
            return res.status(400).json({
                message:"Email and Password are required!"
            });
        };

        //check if the user already exist with this email
        const user = await userModel.findOne({email});
        if(!user){
            return res.status(401).json({
                message:"wrong or invalid email or password!"
            });
        };

        //check the password is valid or not
        const isPasswordValid = await bcrypt.compare(password,user.password);
        if(!isPasswordValid){
            return res.status(401).json({
                message:"Invalid email or password"
            });
        };

        //create token with jsonwebtoken
        const token = jwt.sign(
            {id:user._id},//user._id is automatically generated by MongoDB
            process.env.JWT_SECRET,
            {expiresIn:"1d"}
        );
        return res.status(200).json({
            message:"Log in successfull",
            user:{
                name:user.name,
                email:user.email,
                role:user.role,
            },
            token
        })
    }catch(error){
        return res.status(500).json({
            message:error.message
        })
    }
}

module.exports = {register,login}

// Yes — user._id is automatically generated by MongoDB, the moment a document is created (you saw this earlier as the "locker number" analogy — every document gets one automatically, unique across the entire collection). You don't set it yourself; MongoDB does it for you.

// Why do we put id: user._id inside the JWT, specifically? Here's the reasoning to tie it together: the token needs to somehow "remember" who this login belongs to, so that on future requests, your protectMiddleware can look up the right user again. By putting user._id inside the token payload, later — when the token comes back on some future request — protectMiddleware can do jwt.verify(token) to get that id back out, then do userModel.findById(decoded.id) to fetch that exact same user again. It's how the token "carries" identity forward across requests, without the server needing to remember anything itself (this connects back to the "stateless" idea from earlier)